- name: Install MariaDB
  apt:
    name:
      - mariadb-server
      - python3-pymysql
    state: present

- name: Create User mysql
  mysql_user:
    name: "{{mysql_user_name}}"
    password: "{{mysql_user_password}}"
    login_user: "{{mysql_user_name}}"
    login_password: "{{mysql_user_password}}"
    login_host: "{{mysql_host}}"
    login_port: "{{mysql_port}}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: yes
    state: present

- name: Create database test
  mysql_db:
    name: "{{database_name}}"
    encoding: utf8mb4
    state: present
    login_user: "{{mysql_user_name}}"
    login_password: "{{mysql_user_password}}"

- name: Import database from file
  mysql_db:
    name: "{{database_name}}"
    state: import
    target: /{{database_import_file}}
    login_user: "{{mysql_user_name}}"
    login_password: "{{mysql_user_password}}"
